jeap.reaction.observer.read-user.username=read
jeap.reaction.observer.read-user.password={noop}secret
jeap.reaction.observer.write-user.username=write
jeap.reaction.observer.write-user.password={noop}secret
jeap.reaction.observer.service.statistics-period-in-days=30
jeap.reaction.observer.service.data-aggregation-cron-expression=0 0 1 * * *
jeap.reaction.observer.service.housekeeping-observed-reactions-cron-expression=0 0 3 * * *
jeap.reaction.observer.service.housekeeping-aggregated-data-cron-expression=0 0 5 * * *
jeap.swagger.status=OPEN

spring.application.name=jeap-reaction-observer
server.servlet.context-path=/${spring.application.name}
server.port=8080

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name="hikari-cp-${spring.application.name}"
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common
