<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ch.admin.bit.jeap</groupId>
        <artifactId>jeap-reaction-observer-service</artifactId>
        <version>2.28.0-SNAPSHOT</version>
    </parent>

    <artifactId>jeap-reaction-observer-service-test</artifactId>
    <name>${project.groupId}:${project.artifactId}</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-messaging-infrastructure-kafka-test</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-messaging-avro</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.admin.bit.jeap.messagetype.jeap</groupId>
            <artifactId>reaction-identified-event</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>ch.admin.bit.jeap.messagetype.jeap</groupId>
            <artifactId>reaction-identified-event</artifactId>
            <version>2.0.0</version>
            <classifier>2.0.0</classifier>
        </dependency>
        <dependency>
            <groupId>ch.admin.bit.jeap.messagetype.jeap</groupId>
            <artifactId>reactions-observed-event</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>ch.admin.bit.jeap</groupId>
            <artifactId>jeap-reaction-observer-domain</artifactId>
        </dependency>
    </dependencies>
</project>
